### ISSUE TITLE
After installing, I get error when running any docker command

### ISSUE THREAD

**Issue by mrapogee** [dokku/dokku-mariadb#38]
```
/home/dokku/.basher/bash: main: command not found
Access Denied
````

I get this for every command. Any clue what's going on?

**Comment by mrapogee** [comment]
Looks like it was a storage issue

**Comment by greyrain** [comment]
@mrapogee I have same problem. Is this problem of HDD free space?

**Comment by greyrain** [comment]
I found, it was HDD free space problem.
Command `docker rm -v $(docker ps -a -q -f status=exited)` removes docker exited containers and cleans space on HDD. So, dokku command works again.

**Comment by christiangenco** [comment]
I tried cleaning up exited docker containers and still had 99% disk usage, so I ran this command to find large files on disk:

    find / -type f -size +100000k -exec ls -lh {} \;

Which showed me a 20G (!!!) log file:
    
    -rw-r----- 1 root root 20G Mar 16 22:20 /var/lib/docker/containers/90483b69c0333440528843bd76c74f62118d0e4c01b87c520344f536a0f82c70/90483b69c0333440528843bd76c74f62118d0e4c01b87c520344f536a0f82c70-json.log

Which I cleared out with:

    $ echo > /var/lib/docker/containers/90483b69c0333440528843bd76c74f62118d0e4c01b87c520344f536a0f82c70/90483b69c0333440528843bd76c74f62118d0e4c01b87c520344f536a0f82c70-json.log

Dokku has been so stable I haven't pushed or had to restart in a while (uptime 115 days and counting) - I should probably put this on a cron job, but I'll probably end up just waiting another 100 days and do it manually again.

**Comment by josegonzalez** [comment]
You might want to figure out why you have a 20gb log file, and how to rotate that automatically.

**Comment by haseeb-ahmad** [comment]
@greyrain 's solutions worked well to free up the space on my server but **don't ever use** this command:
> docker rm -v $(docker ps -a -q -f status=exited)
Although **main: command not found** issue was resolved but I ended up losing my postgresql database container and its data on the disk because of **-v** which was exited state I don't know why.

**Comment by josegonzalez** [comment]
The data is always on disk, we don't use volumes or anything. If you stop/start the service again, you should be fine.

**Comment by FilipLukac** [comment]
I had the same issue, because we are running console command right in docker container like:

`dokku run app php www/index.php app:emails:send` and it creates container every single time, when command `dokku run *` is executed.

So I solved it with cron 

`*/3 * * * * docker rm -v $(docker ps -a -q -f status=exited)`

@josegonzalez - is this (dokku / docker) issue or feature ??

**Comment by josegonzalez** [comment]
You need to add the `--rm` flag to the `dokku run` command, as documented [here](http://dokku.viewdocs.io/dokku/deployment/one-off-processes/).

**Comment by josegonzalez** [comment]
Please file new issues in the appropriate repo if you see something similar.
